apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ctlplane
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ctlplane",
      "type": "macvlan",
      "master": "ctlplane",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ ctlplane_subnet }},
        "range_start": "{{ ctlplane_subnet_start }}",
        "range_end": "{{ ctlplane_subnet_end }}"
       }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: internalapi
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "macvlan",
      "master": "internalapi",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ internalapi_subnet }}",
        "range_start": "{{ internalapi_subnet_start }}",
        "range_end": "{{ internalapi_subnet_end }}"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage",
      "type": "macvlan",
      "master": "enp4s0",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ storage_subnet }}",
        "range_start": "{{ storage_subnet_start }}",
        "range_end": "{{ storage_subnet_end }}"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: tenant
  name: tenant
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant",
      "type": "macvlan",
      "master": "tenant",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ tenant_subnet }}",
        "range_start": "{{ tenant_subnet_start }}",
        "range_end": "{{ tenant_subnet_end }}"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: external
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "external",
      "type": "macvlan",
      "master": "external",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ external_subnet }}",
        "range_start": "{{ external_subnet_start }}",
        "range_end": "{{ external_subnet_end }}"
        }
      }
