apiVersion: v1
data:
  AdminPassword: {{ services_key }}
  AodhPassword: {{ services_key }}
  AodhDatabasePassword: {{ services_key }}
  BarbicanDatabasePassword: {{ services_key }}
  BarbicanPassword: {{ services_key }}
  BarbicanSimpleCryptoKEK: {{ services_key }}
  CeilometerPassword: {{ services_key }}
  CinderDatabasePassword: {{ services_key }}
  CinderPassword: {{ services_key }}
  DatabasePassword: {{ services_key }}
  DbRootPassword: {{ services_key }}
  DesignateDatabasePassword: {{ services_key }}
  DesignatePassword: {{ services_key }}
  GlanceDatabasePassword: {{ services_key }}
  GlancePassword: {{ services_key }}
  HeatAuthEncryptionKey: {{ services_key }}
  HeatDatabasePassword: {{ services_key }}
  HeatPassword: {{ services_key }}
  IronicDatabasePassword: {{ services_key }}
  IronicInspectorDatabasePassword: {{ services_key }}
  IronicInspectorPassword: {{ services_key }}
  IronicPassword: {{ services_key }}
  KeystoneDatabasePassword: {{ services_key }}
  ManilaDatabasePassword: {{ services_key }}
  ManilaPassword: {{ services_key }}
  MetadataSecret: {{ services_key }}
  NeutronDatabasePassword: {{ services_key }}
  NeutronPassword: {{ services_key }}
  NovaAPIDatabasePassword: {{ services_key }}
  NovaAPIMessageBusPassword: {{ services_key }}
  NovaCell0DatabasePassword: {{ services_key }}
  NovaCell0MessageBusPassword: {{ services_key }}
  NovaCell1DatabasePassword: {{ services_key }}
  NovaCell1MessageBusPassword: {{ services_key }}
  NovaPassword: {{ services_key }}
  OctaviaDatabasePassword: {{ services_key }}
  OctaviaPassword: {{ services_key }}
  PlacementDatabasePassword: {{ services_key }}
  PlacementPassword: {{ services_key }}
  SwiftPassword: {{ services_key }}
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
