---
- name: Configure NMState on the Control Plane
  kubernetes.core.k8s:
    state: present
    src: ~/templates/rhoso_nncp.yaml

- name: Configure Network Attachement Definitions on the Control Plane
  kubernetes.core.k8s:
    state: present
    src: ~/templates/rhoso_net-attach-def.yaml

- name: Configure MetalLB IP address ranges on the Control Plane
  kubernetes.core.k8s:
    state: present
    src: ~/templates/openstack-ipaddresspools.yaml
    
- name: Configure L2Advertisements on the Control Plane
  kubernetes.core.k8s:
    state: present
    src: ~/templates/openstack-l2advertisement.yaml

- name: Configure Services Secrets on the Control Plane
  kubernetes.core.k8s:
    state: present
    src: ~/templates/openstack_service_secret.yaml

- name: Configure Libvirt Secret for Live Migration on the Control Plane
  kubernetes.core.k8s:
    state: present
    src: ~/templates/secret_libvirt.yaml

